<?php declare(strict_types=1);

namespace Lemonade\Postcode;

enum CountryCode: string
{
    case AF = 'AF'; // Afghanistan - 004
    case AL = 'AL'; // Albania - 008
    case DZ = 'DZ'; // Algeria - 012
    case AS = 'AS'; // American Samoa - 016
    case AD = 'AD'; // Andorra - 020
    case AO = 'AO'; // Angola - 024
    case AI = 'AI'; // Anguilla - 660
    case AQ = 'AQ'; // Antarctica - 010
    case AG = 'AG'; // Antigua and Barbuda - 028
    case AR = 'AR'; // Argentina - 032
    case AM = 'AM'; // Armenia - 051
    case AW = 'AW'; // Aruba - 533
    case AU = 'AU'; // Australia - 036
    case AT = 'AT'; // Austria - 040
    case AZ = 'AZ'; // Azerbaijan - 031
    case BS = 'BS'; // Bahamas (the) - 044
    case BH = 'BH'; // Bahrain - 048
    case BD = 'BD'; // Bangladesh - 050
    case BB = 'BB'; // Barbados - 052
    case BY = 'BY'; // Belarus - 112
    case BE = 'BE'; // Belgium - 056
    case BZ = 'BZ'; // Belize - 084
    case BJ = 'BJ'; // Benin - 204
    case BM = 'BM'; // Bermuda - 060
    case BT = 'BT'; // Bhutan - 064
    case BO = 'BO'; // Bolivia (Plurinational State of) - 068
    case BQ = 'BQ'; // Bonaire, Sint Eustatius and Saba - 535
    case BA = 'BA'; // Bosnia and Herzegovina - 070
    case BW = 'BW'; // Botswana - 072
    case BV = 'BV'; // Bouvet Island - 074
    case BR = 'BR'; // Brazil - 076
    case IO = 'IO'; // British Indian Ocean Territory (the) - 086
    case BN = 'BN'; // Brunei Darussalam - 096
    case BG = 'BG'; // Bulgaria - 100
    case BF = 'BF'; // Burkina Faso - 854
    case BI = 'BI'; // Burundi - 108
    case CV = 'CV'; // Cabo Verde - 132
    case KH = 'KH'; // Cambodia - 116
    case CM = 'CM'; // Cameroon - 120
    case CA = 'CA'; // Canada - 124
    case KY = 'KY'; // Cayman Islands (the) - 136
    case CF = 'CF'; // Central African Republic (the) - 140
    case TD = 'TD'; // Chad - 148
    case CL = 'CL'; // Chile - 152
    case CN = 'CN'; // China - 156
    case CX = 'CX'; // Christmas Island - 162
    case CC = 'CC'; // Cocos (Keeling) Islands (the) - 166
    case CO = 'CO'; // Colombia - 170
    case KM = 'KM'; // Comoros (the) - 174
    case CD = 'CD'; // Congo (the Democratic Republic of the) - 180
    case CG = 'CG'; // Congo (the) - 178
    case CK = 'CK'; // Cook Islands (the) - 184
    case CR = 'CR'; // Costa Rica - 188
    case HR = 'HR'; // Croatia - 191
    case CU = 'CU'; // Cuba - 192
    case CW = 'CW'; // Curaçao - 531
    case CY = 'CY'; // Cyprus - 196
    case CZ = 'CZ'; // Czechia - 203
    case CI = 'CI'; // Côte d'Ivoire - 384
    case DK = 'DK'; // Denmark - 208
    case DJ = 'DJ'; // Djibouti - 262
    case DM = 'DM'; // Dominica - 212
    case DO = 'DO'; // Dominican Republic (the) - 214
    case EC = 'EC'; // Ecuador - 218
    case EG = 'EG'; // Egypt - 818
    case SV = 'SV'; // El Salvador - 222
    case GQ = 'GQ'; // Equatorial Guinea - 226
    case ER = 'ER'; // Eritrea - 232
    case EE = 'EE'; // Estonia - 233
    case SZ = 'SZ'; // Eswatini - 748
    case ET = 'ET'; // Ethiopia - 231
    case FK = 'FK'; // Falkland Islands (the) [Malvinas] - 238
    case FO = 'FO'; // Faroe Islands (the) - 234
    case FJ = 'FJ'; // Fiji - 242
    case FI = 'FI'; // Finland - 246
    case FR = 'FR'; // France - 250
    case GF = 'GF'; // French Guiana - 254
    case PF = 'PF'; // French Polynesia - 258
    case TF = 'TF'; // French Southern Territories (the) - 260
    case GA = 'GA'; // Gabon - 266
    case GM = 'GM'; // Gambia (the) - 270
    case GE = 'GE'; // Georgia - 268
    case DE = 'DE'; // Germany - 276
    case GH = 'GH'; // Ghana - 288
    case GI = 'GI'; // Gibraltar - 292
    case GR = 'GR'; // Greece - 300
    case GL = 'GL'; // Greenland - 304
    case GD = 'GD'; // Grenada - 308
    case GP = 'GP'; // Guadeloupe - 312
    case GU = 'GU'; // Guam - 316
    case GT = 'GT'; // Guatemala - 320
    case GG = 'GG'; // Guernsey - 831
    case GN = 'GN'; // Guinea - 324
    case GW = 'GW'; // Guinea-Bissau - 624
    case GY = 'GY'; // Guyana - 328
    case HT = 'HT'; // Haiti - 332
    case HM = 'HM'; // Heard Island and McDonald Islands - 334
    case VA = 'VA'; // Holy See (the) - 336
    case HN = 'HN'; // Honduras - 340
    case HK = 'HK'; // Hong Kong - 344
    case HU = 'HU'; // Hungary - 348
    case IS = 'IS'; // Iceland - 352
    case IN = 'IN'; // India - 356
    case ID = 'ID'; // Indonesia - 360
    case IR = 'IR'; // Iran (Islamic Republic of) - 364
    case IQ = 'IQ'; // Iraq - 368
    case IE = 'IE'; // Ireland - 372
    case IM = 'IM'; // Isle of Man - 833
    case IL = 'IL'; // Israel - 376
    case IT = 'IT'; // Italy - 380
    case JM = 'JM'; // Jamaica - 388
    case JP = 'JP'; // Japan - 392
    case JE = 'JE'; // Jersey - 832
    case JO = 'JO'; // Jordan - 400
    case KZ = 'KZ'; // Kazakhstan - 398
    case KE = 'KE'; // Kenya - 404
    case KI = 'KI'; // Kiribati - 296
    case KP = 'KP'; // Korea (the Democratic People's Republic of) - 408
    case KR = 'KR'; // Korea (the Republic of) - 410
    case KW = 'KW'; // Kuwait - 414
    case KG = 'KG'; // Kyrgyzstan - 417
    case LA = 'LA'; // Lao People's Democratic Republic (the) - 418
    case LV = 'LV'; // Latvia - 428
    case LB = 'LB'; // Lebanon - 422
    case LS = 'LS'; // Lesotho - 426
    case LR = 'LR'; // Liberia - 430
    case LY = 'LY'; // Libya - 434
    case LI = 'LI'; // Liechtenstein - 438
    case LT = 'LT'; // Lithuania - 440
    case LU = 'LU'; // Luxembourg - 442
    case MO = 'MO'; // Macao - 446
    case MG = 'MG'; // Madagascar - 450
    case MW = 'MW'; // Malawi - 454
    case MY = 'MY'; // Malaysia - 458
    case MV = 'MV'; // Maldives - 462
    case ML = 'ML'; // Mali - 466
    case MT = 'MT'; // Malta - 470
    case MH = 'MH'; // Marshall Islands (the) - 584
    case MQ = 'MQ'; // Martinique - 474
    case MR = 'MR'; // Mauritania - 478
    case MU = 'MU'; // Mauritius - 480
    case YT = 'YT'; // Mayotte - 175
    case MX = 'MX'; // Mexico - 484
    case FM = 'FM'; // Micronesia (Federated States of) - 583
    case MD = 'MD'; // Moldova (the Republic of) - 498
    case MC = 'MC'; // Monaco - 492
    case MN = 'MN'; // Mongolia - 496
    case ME = 'ME'; // Montenegro - 499
    case MS = 'MS'; // Montserrat - 500
    case MA = 'MA'; // Morocco - 504
    case MZ = 'MZ'; // Mozambique - 508
    case MM = 'MM'; // Myanmar - 104
    case NA = 'NA'; // Namibia - 516
    case NR = 'NR'; // Nauru - 520
    case NP = 'NP'; // Nepal - 524
    case NL = 'NL'; // Netherlands (the) - 528
    case NC = 'NC'; // New Caledonia - 540
    case NZ = 'NZ'; // New Zealand - 554
    case NI = 'NI'; // Nicaragua - 558
    case NE = 'NE'; // Niger (the) - 562
    case NG = 'NG'; // Nigeria - 566
    case NU = 'NU'; // Niue - 570
    case NF = 'NF'; // Norfolk Island - 574
    case MP = 'MP'; // Northern Mariana Islands (the) - 580
    case NO = 'NO'; // Norway - 578
    case OM = 'OM'; // Oman - 512
    case PK = 'PK'; // Pakistan - 586
    case PW = 'PW'; // Palau - 585
    case PS = 'PS'; // Palestine, State of - 275
    case PA = 'PA'; // Panama - 591
    case PG = 'PG'; // Papua New Guinea - 598
    case PY = 'PY'; // Paraguay - 600
    case PE = 'PE'; // Peru - 604
    case PH = 'PH'; // Philippines (the) - 608
    case PN = 'PN'; // Pitcairn - 612
    case PL = 'PL'; // Poland - 616
    case PT = 'PT'; // Portugal - 620
    case PR = 'PR'; // Puerto Rico - 630
    case QA = 'QA'; // Qatar - 634
    case MK = 'MK'; // Republic of North Macedonia - 807
    case RO = 'RO'; // Romania - 642
    case RU = 'RU'; // Russian Federation (the) - 643
    case RW = 'RW'; // Rwanda - 646
    case RE = 'RE'; // Réunion - 638
    case BL = 'BL'; // Saint Barthélemy - 652
    case SH = 'SH'; // Saint Helena, Ascension and Tristan da Cunha - 654
    case KN = 'KN'; // Saint Kitts and Nevis - 659
    case LC = 'LC'; // Saint Lucia - 662
    case MF = 'MF'; // Saint Martin (French part) - 663
    case PM = 'PM'; // Saint Pierre and Miquelon - 666
    case VC = 'VC'; // Saint Vincent and the Grenadines - 670
    case WS = 'WS'; // Samoa - 882
    case SM = 'SM'; // San Marino - 674
    case ST = 'ST'; // Sao Tome and Principe - 678
    case SA = 'SA'; // Saudi Arabia - 682
    case SN = 'SN'; // Senegal - 686
    case RS = 'RS'; // Serbia - 688
    case SC = 'SC'; // Seychelles - 690
    case SL = 'SL'; // Sierra Leone - 694
    case SG = 'SG'; // Singapore - 702
    case SX = 'SX'; // Sint Maarten (Dutch part) - 534
    case SK = 'SK'; // Slovakia - 703
    case SI = 'SI'; // Slovenia - 705
    case SB = 'SB'; // Solomon Islands - 090
    case SO = 'SO'; // Somalia - 706
    case ZA = 'ZA'; // South Africa - 710
    case GS = 'GS'; // South Georgia and the South Sandwich Islands - 239
    case SS = 'SS'; // South Sudan - 728
    case ES = 'ES'; // Spain - 724
    case LK = 'LK'; // Sri Lanka - 144
    case SD = 'SD'; // Sudan (the) - 729
    case SR = 'SR'; // Suriname - 740
    case SJ = 'SJ'; // Svalbard and Jan Mayen - 744
    case SE = 'SE'; // Sweden - 752
    case CH = 'CH'; // Switzerland - 756
    case SY = 'SY'; // Syrian Arab Republic - 760
    case TW = 'TW'; // Taiwan (Province of China) - 158
    case TJ = 'TJ'; // Tajikistan - 762
    case TZ = 'TZ'; // Tanzania, United Republic of - 834
    case TH = 'TH'; // Thailand - 764
    case TL = 'TL'; // Timor-Leste - 626
    case TG = 'TG'; // Togo - 768
    case TK = 'TK'; // Tokelau - 772
    case TO = 'TO'; // Tonga - 776
    case TT = 'TT'; // Trinidad and Tobago - 780
    case TN = 'TN'; // Tunisia - 788
    case TR = 'TR'; // Turkey - 792
    case TM = 'TM'; // Turkmenistan - 795
    case TC = 'TC'; // Turks and Caicos Islands (the) - 796
    case TV = 'TV'; // Tuvalu - 798
    case UG = 'UG'; // Uganda - 800
    case UA = 'UA'; // Ukraine - 804
    case AE = 'AE'; // United Arab Emirates (the) - 784
    case GB = 'GB'; // United Kingdom of Great Britain and Northern Ireland (the) - 826
    case UM = 'UM'; // United States Minor Outlying Islands (the) - 581
    case US = 'US'; // United States of America (the) - 840
    case UY = 'UY'; // Uruguay - 858
    case UZ = 'UZ'; // Uzbekistan - 860
    case VU = 'VU'; // Vanuatu - 548
    case VE = 'VE'; // Venezuela (Bolivarian Republic of) - 862
    case VN = 'VN'; // Viet Nam - 704
    case VG = 'VG'; // Virgin Islands (British) - 092
    case VI = 'VI'; // Virgin Islands (U.S.) - 850
    case WF = 'WF'; // Wallis and Futuna - 876
    case EH = 'EH'; // Western Sahara - 732
    case YE = 'YE'; // Yemen - 887
    case ZM = 'ZM'; // Zambia - 894
    case ZW = 'ZW'; // Zimbabwe - 716
    case AX = 'AX'; // Åland Islands - 248
}
